# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='imgLink',
            field=models.CharField(default='http://images.hacktabs.com//2012/07/404-not-found.gif', max_length=200),
        ),
    ]
