# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_cadeira_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
