# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_tema_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('faculdade', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tema',
            name='views',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
