# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_auto_20170114_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imgLink',
            field=models.CharField(default='http://images.hacktabs.com//2012/07/404-not-found.gif', max_length=200),
        ),
    ]
