# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_curso_imglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='Curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.Curso'),
            preserve_default=False,
        ),
    ]
